---
# This is required before enabling or disabling linger.
- name: Start and enable systemd-logind
  ansible.builtin.service:
    enabled: true
    name: systemd-logind
    state: started

# This causes the user's user-specific systemd session to start on
# boot instead of only when that user logs in.  We need the user's
# session to be active so we can enable the user-mode systemd service,
# so we use the trick of enabling linger for the user, enabling the
# user-mode service, then disabling linger for the user.
#
# This fiddling with linger does lead to some idempotence funkiness
# for this role, so we have to make use of changed_when: false for
# those two tasks.
- name: Enable linger for user
  ansible.builtin.command:
    argv:
      - /bin/loginctl
      - enable-linger
      - "{{ username }}"
    creates: /var/lib/systemd/linger/{{ username }}
  # This changed_when is necessary to pass idempotence.  We cannot use
  # the molecule-idempotence-notest tag here because the command must
  # run; otherwise, the task the follows will fail.  See
  # ansible/molecule#2765 for more details.
  changed_when: false

- name: >-
    Enable the user-mode systemd service that creates the file share symlink
    for the user
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: create-fileshare-symlink
    scope: user
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  vars:
    # This is necessary to get around the difficult case where you ssh
    # into a machine as an unprivileged user _and_ become a different
    # unprivileged user:
    # https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_ssh_pipelining: true

# Now that the user-mode service has been enabled we can disable
# linger for the user.
- name: Disable linger for user
  ansible.builtin.command:
    argv:
      - /bin/loginctl
      - disable-linger
      - "{{ username }}"
    removes: /var/lib/systemd/linger/{{ username }}
  # This changed_when is necessary to pass idempotence.  We cannot use
  # the molecule-idempotence-notest tag here because the command must
  # run; otherwise, the user will needlessly have linger enabled.  See
  # ansible/molecule#2765 for more details.
  changed_when: false
