---
- name: Delete font cache
  file:
    state: absent
    path: /var/cache/fontconfig
  listen: "rebuild font cache"

- name: Build font cache
  command:
    cmd: fc-cache -v
    creates: /var/cache/fontconfig
  listen: "rebuild font cache"
