---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-xfce-cool
      ansible.builtin.include_role:
        name: ansible-role-xfce-cool
      vars:
        usernames:
          - test
