---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible_role_xfce-cool
      ansible.builtin.include_role:
        name: xfce_cool
      vars:
        xfce_cool_usernames:
          - test
