---
# This molecule configuration file is suitable for testing Ansible
# roles that _do not_ require SystemD.  If your Ansible role _does_
# require SystemD then you should use molecule-with-systemd.yml
# instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  # Amazon Linux does not appear to offer Xfce
  # - name: amazonlinux2
  #   image: amazonlinux:2
  - name: debian10
    image: debian:buster-slim
  - name: debian11
    image: debian:bullseye-slim
  - name: kali
    image: kalilinux/kali-rolling
  - name: fedora32
    image: fedora:32
  - name: fedora33
    image: fedora:33
  - name: ubuntu18
    image: ubuntu:bionic
  - name: ubuntu20
    image: ubuntu:focal
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests
