---
# This is necessary to setup for the test_symlink_exists() test that
# is run in the verify stage.  Setting up this test user allows to
# test the contents of the user-mode systemd service deployed by this
# role.
- name: Create and configure a test user
  hosts: all
  tasks:
    - name: >-
        Start the user-mode systemd service that creates the file share
        symlink for the test user
      ansible.builtin.systemd:
        name: create-fileshare-symlink
        scope: user
        state: started
      become: yes
      become_user: "{{ username }}"
  vars:
    # The username of the test user
    username: test
