---
# This molecule configuration file is suitable for testing Ansible
# roles that _do_ require SystemD.  If your Ansible role _does not_
# require SystemD then you should use molecule-no-systemd.yml instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian10-systemd
    image: geerlingguy/docker-debian10-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: debian11-systemd
    image: geerlingguy/docker-debian11-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: debian12-systemd
    image: cisagov/docker-debian12-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: kali-systemd
    image: cisagov/docker-kali-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: ubuntu-18-systemd
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: ubuntu-20-systemd
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
provisioner:
  name: ansible
scenario:
  name: debian
verifier:
  name: testinfra
  directory: ../tests
