---
# This molecule configuration file is suitable for testing Ansible
# roles that _do_ require SystemD.  If your Ansible role _does not_
# require SystemD then you should use molecule-no-systemd.yml instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # Amazon Linux 2023 does not currently offer Xfce
  # https://docs.aws.amazon.com/linux/al2023/release-notes/all-packages-al2023-20230419.html
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: geerlingguy/docker-amazonlinux2023-ansible:latest
  #   name: amazonlinux2023-systemd
  #   platform: amd64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora37-ansible:latest
    name: fedora37-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora38-ansible:latest
    name: fedora38-systemd
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
scenario:
  name: redhat
verifier:
  name: testinfra
  directory: ../tests
