---
# This molecule configuration file is suitable for testing Ansible
# roles that _do_ require SystemD.  If your Ansible role _does not_
# require SystemD then you should use molecule-no-systemd.yml instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  # Amazon Linux does not appear to offer Xfce
  # - name: amazonlinux2_systemd
  #   image: geerlingguy/docker-amazonlinux2-ansible:latest
  #   privileged: yes
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   command: /lib/systemd/systemd
  #   pre_build_image: yes
  - name: fedora32_systemd
    image: geerlingguy/docker-fedora32-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
  - name: fedora33_systemd
    image: geerlingguy/docker-fedora33-ansible:latest
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /lib/systemd/systemd
    pre_build_image: yes
provisioner:
  name: ansible
scenario:
  name: redhat
verifier:
  name: testinfra
  directory: ../tests
